const data = [
    // Aliments i begudes
    { e: "🍎", w: "poma" }, { e: "🍞", w: "pa" }, { e: "🥛", w: "llet" }, { e: "🍌", w: "plàtan" }, { e: "🧀", w: "formatge" },
    { e: "🥚", w: "ou" }, { e: "🥕", w: "pastanaga" }, { e: "🍗", w: "pollastre" }, { e: "🐟", w: "peix" }, { e: "🍦", w: "gelat" },
    { e: "🍕", w: "pizza" }, { e: "🍓", w: "maduixa" }, { e: "🍊", w: "taronja" }, { e: "🍉", w: "síndria" }, { e: "🥔", w: "patata" },
    { e: "🍅", w: "tomàquet" }, { e: "🍚", w: "arròs" }, { e: "🍫", w: "xocolata" }, { e: "💧", w: "aigua" }, { e: "🧃", w: "suc" },
    // Animals
    { e: "🐶", w: "gos" }, { e: "🐱", w: "gat" }, { e: "🐭", w: "ratolí" }, { e: "🐰", w: "conill" }, { e: "🦊", w: "guineu" },
    { e: "🐻", w: "os" }, { e: "🐼", w: "panda" }, { e: "🦁", w: "lleó" }, { e: "🐮", w: "vaca" }, { e: "🐷", w: "porc" },
    { e: "🐵", w: "mono" }, { e: "🐸", w: "granota" }, { e: "🐦", w: "ocell" }, { e: "🐧", w: "pingüí" }, { e: "🦆", w: "ànec" },
    { e: "🐝", w: "abella" }, { e: "🕷️", w: "aranya" }, { e: "🐢", w: "tortuga" }, { e: "🐬", w: "dofí" }, { e: "🐎", w: "cavall" },
    // Accions / Verbs
    { e: "🏃", w: "córrer" }, { e: "🍽️", w: "menjar" }, { e: "🥤", w: "beure" }, { e: "😴", w: "dormir" }, { e: "📖", w: "llegir" },
    { e: "✍️", w: "escriure" }, { e: "🗣️", w: "parlar" }, { e: "🎵", w: "cantar" }, { e: "💃", w: "ballar" }, { e: "🚶", w: "caminar" },
    { e: "🏊", w: "nedar" }, { e: "🚴", w: "pedalar" }, { e: "🎨", w: "pintar" }, { e: "🧼", w: "rentar" }, { e: "🧠", w: "pensar" },
    { e: "🤝", w: "ajudar" }, { e: "🧗", w: "pujar" }, { e: "✂️", w: "tallar" }, { e: "🧹", w: "escombrar" }, { e: "🛒", w: "comprar" },
    // Objectes de casa i escola
    { e: "🏠", w: "casa" }, { e: "🪑", w: "cadira" }, { e: "🛏️", w: "llit" }, { e: "🔑", w: "clau" }, { e: "🚪", w: "porta" },
    { e: "🧸", w: "nino" }, { e: "🎒", w: "motxilla" }, { e: "✏️", w: "llapis" }, { e: "📚", w: "llibre" }, { e: "💻", w: "ordinador" },
    { e: "📱", w: "mòbil" }, { e: "📺", w: "televisió" }, { e: "👕", w: "samarreta" }, { e: "👟", w: "sabata" }, { e: "👓", w: "ulleres" },
    { e: "🌂", w: "parany" }, { e: "🚲", w: "bicicleta" }, { e: "⏰", w: "rellotge" }, { e: "🧼", w: "sabó" }, { e: "🥄", w: "cullerot" },
    // Natura i transport
    { e: "☀️", w: "sol" }, { e: "🌙", w: "lluna" }, { e: "⭐", w: "estel" }, { e: "☁️", w: "núvol" }, { e: "🌧️", w: "pluja" },
    { e: "❄️", w: "neu" }, { e: "🔥", w: "foc" }, { e: "🌳", w: "arbre" }, { e: "🌸", w: "flor" }, { e: "🚗", w: "cotxe" },
    { e: "🚌", w: "autobús" }, { e: "🚂", w: "tren" }, { e: "✈️", w: "avió" }, { e: "⛵", w: "vaixell" }, { e: "🚀", w: "coet" }
];

const frasesComplexes = [
    { text: "El nen menja una poma vermella", ordre: ["👦", "🍽️", "🍎", "🔴"] },
    { text: "La nena llegeix un llibre gran", ordre: ["👧", "📖", "📚", "🏢"] },
    { text: "El gos corre feliç pel parc", ordre: ["🐶", "🏃", "😀", "🌳"] },
    { text: "El gat negre dorm al llit", ordre: ["🐱", "⚫", "😴", "🛏️"] },
    { text: "El nen beu llet freda a casa", ordre: ["👦", "🥤", "🥛", "🏠"] },
    { text: "La nena pinta una flor bonica", ordre: ["👧", "🎨", "🌸", "❤️"] },
    { text: "El mico menja un plàtan groc", ordre: ["🐵", "🍽️", "🍌", "🟡"] },
    { text: "El ocell vola pel cel blau", ordre: ["🐦", "🚀", "☁️", "🔵"] },
    { text: "El cavall corre ràpid sota el sol", ordre: ["🐎", "🏃", "⚡", "☀️"] },
    { text: "El peix neda content a l'aigua", ordre: ["🐟", "🏊", "😀", "💧"] },
    { text: "La vaca menja herba verda al camp", ordre: ["🐄", "🍽️", "🌿", "🟢", "🌾"] },
    { text: "El conill salta pel jardí florit", ordre: ["🐰", "🦘", "🌷", "🌳"] },
    { text: "La mare cuina sopa calenta a la cuina", ordre: ["👩", "👩‍🍳", "🍲", "🔥", "🏠"] },
    { text: "El pare condueix el cotxe blau", ordre: ["👨", "🚗", "🔵", "🛣️"] },
    { text: "L'àvia rega les plantes del balcó", ordre: ["👵", "💧", "🪴", "🏢"] },
    { text: "L'avi llegeix el diari al sofà", ordre: ["👴", "📰", "📖", "🛋️"] },
    { text: "La mestra escriu a la pissarra gran", ordre: ["👩‍🏫", "✍️", "🟩", "🏫"] },
    { text: "L'alumne resol un problema difícil", ordre: ["🧑", "✏️", "➕", "🤔"] },
    { text: "El bomber apaga un incendi gran", ordre: ["👨‍🚒", "💧", "🔥", "🏢"] },
    { text: "La metgessa cura un nen malalt", ordre: ["👩‍⚕️", "💊", "👦", "🤒"] },
    { text: "El policia vigila el carrer tranquil", ordre: ["👮", "👀", "🛣️", "🙂"] },
    { text: "La cuinera prepara un pastís dolç", ordre: ["👩‍🍳", "🎂", "🍓", "😋"] },
    { text: "El músic toca una guitarra nova", ordre: ["🎸", "🎵", "🧑", "✨"] },
    { text: "La cantant interpreta una cançó alegre", ordre: ["👩", "🎤", "🎶", "😀"] },
    { text: "El pintor dibuixa un paisatge bonic", ordre: ["🧑‍🎨", "🎨", "🏞️", "❤️"] },
    { text: "La noia passeja amb el seu gos", ordre: ["👧", "🚶", "🐶", "🌳"] },
    { text: "El noi juga a futbol amb amics", ordre: ["👦", "⚽", "👬", "🏃"] },
    { text: "Els nens construeixen un castell de sorra", ordre: ["👦", "👧", "🏰", "🏖️"] },
    { text: "La família sopa junta al menjador", ordre: ["👨", "👩", "👦", "🍽️", "🏠"] },
    { text: "El gat caça un ratolí petit", ordre: ["🐱", "🏃", "🐭", "🤏"] },
    { text: "El gos guarda la casa gran", ordre: ["🐶", "🛡️", "🏠", "🏢"] },
    { text: "La gallina pon un ou blanc", ordre: ["🐔", "🥚", "⚪", "😀"] },
    { text: "L'ànec neda al llac tranquil", ordre: ["🦆", "🏊", "💧", "🙂"] },
    { text: "L'elefant camina per la selva", ordre: ["🐘", "🚶", "🌴", "🌿"] },
    { text: "La girafa menja fulles altes", ordre: ["🦒", "🍽️", "🌿", "⬆️"] },
    { text: "El lleó descansa sota un arbre", ordre: ["🦁", "😴", "🌳", "☀️"] },
    { text: "La zebra corre per la sabana", ordre: ["🦓", "🏃", "🌾", "☀️"] },
    { text: "L'ós pesca un peix al riu", ordre: ["🐻", "🎣", "🐟", "💧"] },
    { text: "El pingüí llisca sobre el gel", ordre: ["🐧", "🛝", "🧊", "❄️"] },
    { text: "El dofí salta fora de l'aigua", ordre: ["🐬", "🦘", "💧", "😀"] },
    { text: "La tortuga camina lentament pel camí", ordre: ["🐢", "🚶", "🐌", "🛣️"] },
    { text: "El cranc camina per la platja", ordre: ["🦀", "🚶", "🏖️", "☀️"] },
    { text: "L'abella recull nèctar de la flor", ordre: ["🐝", "🌸", "🍯", "🌼"] },
    { text: "La papallona vola entre les flors", ordre: ["🦋", "🚀", "🌸", "🌷"] },
    { text: "El nen obre una capsa sorpresa", ordre: ["👦", "📦", "🎁", "😲"] },
    { text: "La nena menja maduixes dolces", ordre: ["👧", "🍓", "😋", "❤️"] },
    { text: "El noi beu suc de taronja", ordre: ["👦", "🥤", "🍊", "😀"] },
    { text: "La noia escriu una carta llarga", ordre: ["👧", "✍️", "📄", "📬"] },
    { text: "El professor explica una lliçó interessant", ordre: ["👨‍🏫", "🗣️", "📚", "🤔"] },
    { text: "L'estudiant estudia per l'examen", ordre: ["🧑", "📖", "✏️", "🎓"] },
    { text: "El científic observa una estrella brillant", ordre: ["🧑‍🔬", "🔭", "⭐", "✨"] },
    { text: "L'astronauta viatja per l'espai", ordre: ["🧑‍🚀", "🚀", "🌍", "⭐"] },
    { text: "El mariner navega pel mar blau", ordre: ["🧑‍✈️", "⛵", "🌊", "🔵"] },
    { text: "La pagesa cull pomes del camp", ordre: ["👩‍🌾", "🍎", "🌳", "🌾"] },
    { text: "El jardiner planta una llavor petita", ordre: ["🧑‍🌾", "🌱", "🤏", "🌿"] },
    { text: "La infermera ajuda un pacient cansat", ordre: ["👩‍⚕️", "🤝", "🧑", "😴"] },
    { text: "El forner prepara pa calent", ordre: ["👨‍🍳", "🍞", "🔥", "😋"] },
    { text: "La nena juga amb una pilota vermella", ordre: ["👧", "⚽", "🔴", "😀"] },
    { text: "El nen construeix una torre alta", ordre: ["👦", "🧱", "🏗️", "⬆️"] },
    { text: "La família visita el zoològic", ordre: ["👨", "👩", "👧", "🦁", "🐘", "🐒"] },
    { text: "Els amics fan un pícnic al parc", ordre: ["👫", "🧺", "🍎", "🌳"] },
    { text: "La mare compra fruita al mercat", ordre: ["👩", "🛒", "🍎", "🍌", "🍓"] },
    { text: "El pare arregla una bicicleta vella", ordre: ["👨", "🔧", "🚲", "⚙️"] },
    { text: "La nena renta les mans amb sabó", ordre: ["👧", "🧼", "👐", "💧"] },
    { text: "El nen es raspalla les dents", ordre: ["👦", "🪥", "😁", "✨"] },
    { text: "El gat mira la lluna plena", ordre: ["🐱", "👀", "🌕", "🌙"] },
    { text: "La granota salta prop de l'estany", ordre: ["🐸", "🦘", "💧", "🌿"] },
    { text: "El ratolí menja formatge groc", ordre: ["🐭", "🍽️", "🧀", "🟡"] },
    { text: "La serp s'amaga entre les pedres", ordre: ["🐍", "🙈", "🪨", "🌿"] },
    { text: "El cangur porta la cria a la bossa", ordre: ["🦘", "👶", "👜", "😀"] },
    { text: "La foca descansa sobre una roca", ordre: ["🦭", "😴", "🪨", "🌊"] },
    { text: "El mussol observa el bosc de nit", ordre: ["🦉", "👀", "🌲", "🌙"] },
    { text: "La guineu corre pel camp silenciós", ordre: ["🦊", "🏃", "🌾", "🤫"] },
    { text: "El llop udola sota la lluna", ordre: ["🐺", "🎵", "🌕", "🌙"] },
    { text: "La cabra puja una muntanya alta", ordre: ["🐐", "⬆️", "⛰️", "☀️"] },
    { text: "El camió transporta caixes pesades", ordre: ["🚚", "📦", "📦", "💪"] },
    { text: "L'avió vola entre els núvols", ordre: ["✈️", "☁️", "☁️", "🔵"] },
    { text: "El tren arriba a l'estació", ordre: ["🚆", "🏫", "⏰", "😀"] },
    { text: "La bicicleta baixa pel carrer", ordre: ["🚲", "⬇️", "🛣️", "😀"] },
    { text: "El vaixell creua l'oceà tranquil", ordre: ["🚢", "🌊", "🙂", "☀️"] },
    { text: "El nen encén una llanterna a la nit", ordre: ["👦", "🔦", "🌙", "✨"] },
    { text: "La nena observa un arc de Sant Martí", ordre: ["👧", "👀", "🌈", "😀"] },
    { text: "Els alumnes entren a l'escola", ordre: ["👦", "👧", "🏫", "🚶"] },
    { text: "La classe escolta la mestra atentament", ordre: ["👂", "👩‍🏫", "📚", "🤫"] },
    { text: "El cuiner talla verdures fresques", ordre: ["👨‍🍳", "🔪", "🥕", "🥦", "😀"] },
    { text: "La família mira una pel·lícula divertida", ordre: ["👨", "👩", "👦", "📺", "😂"] },
    { text: "El nen pesca al riu amb paciència", ordre: ["👦", "🎣", "💧", "🙂"] },
    { text: "La nena munta a cavall pel camp", ordre: ["👧", "🐎", "🌾", "😀"] },
    { text: "El pagès condueix un tractor vermell", ordre: ["👨‍🌾", "🚜", "🔴", "🌾"] },
    { text: "La tempesta porta pluja i vent", ordre: ["⛈️", "🌧️", "💨", "☁️"] },
    { text: "El sol escalfa la sorra de la platja", ordre: ["☀️", "🔥", "🏖️", "😀"] },
    { text: "La neu cobreix la muntanya blanca", ordre: ["❄️", "⛰️", "⚪", "🥶"] },
    { text: "El nen fa un ninot de neu", ordre: ["👦", "⛄", "❄️", "😀"] },
    { text: "La nena obre un paraigua sota la pluja", ordre: ["👧", "☂️", "🌧️", "💧"] },
    { text: "El gat juga amb una pilota petita", ordre: ["🐱", "⚽", "🤏", "😀"] },
    { text: "La mare abraça la seva filla", ordre: ["👩", "🤗", "👧", "❤️"] },
    { text: "El pare llegeix un conte abans de dormir", ordre: ["👨", "📖", "📚", "🌙", "😴"] },
    { text: "Els amics celebren un aniversari especial", ordre: ["👫", "🎂", "🎉", "🎁", "😀"] },
    { text: "La nena canta mentre toca el piano", ordre: ["👧", "🎤", "🎹", "🎶", "😀"] },
    { text: "El nen planta un arbre al jardí", ordre: ["👦", "🌱", "🌳", "🌿"] },
    { text: "La família camina per la muntanya", ordre: ["👨", "👩", "👧", "🚶", "⛰️"] },
    { text: "El gos beu aigua després de córrer", ordre: ["🐶", "🏃", "🥤", "💧"] },
    { text: "La nena troba una petxina a la platja", ordre: ["👧", "🐚", "🏖️", "😲"] },
    { text: "El noi observa peixos de colors", ordre: ["👦", "👀", "🐟", "🌈"] },
    { text: "La família gaudeix d'un dia assolellat", ordre: ["👨", "👩", "👧", "☀️", "😀"] }
];

const situacions = [
    { q: "Està plovent molt fort a fora, què necessites per no banyar-te?", correct: "🌂", opts: ["🪑", "🚲", "🍉", "🚗", "🧸"] },
    { q: "Tens molta gana i vols esmorzar sa, què pots menjar?", correct: "🍎", opts: ["🔑", "🚗", "💻", "🍕", "🚀"] },
    { q: "Fa molta calor i vols anar ràpid a la platja, quin transport agafes?", correct: "🚗", opts: ["🛏️", "🧸", "📚", "🐱", "🚂"] },
    { q: "S'ha fet de nit i estàs molt cansat, on vas directament?", correct: "🛏️", opts: ["🍕", "🚀", "🧼", "🎨", "🍞"] },
    { q: "Vols fer un dibuix molt bonic en un llibre, què fas servir?", correct: "🎨", opts: ["🐱", "🚂", "🍞", "🔑", "💻"] },
    { q: "Vols obrir la porta de casa que està tancada, què necessites?", correct: "🔑", opts: ["🍎", "🚲", "🧸", "🎨", "🐱"] },
    { q: "Vols llegir una història abans d'anar a dormir, què agafes?", correct: "📚", opts: ["🚗", "🍕", "🔨", "🐟", "🧼"] },
    { q: "Tens set després de jugar, què necessites?", correct: "🥤", opts: ["🪑", "🚀", "📚", "🎈", "🐶"] },
    { q: "Vols rentar-te les mans perquè estan brutes, què utilitzes?", correct: "🧼", opts: ["🚲", "🍎", "🎨", "🐱", "📚"] },
    { q: "Has de clavar un clau a la paret, què fas servir?", correct: "🔨", opts: ["🍌", "🚗", "🧸", "📖", "🐦"] },
    { q: "Vols anar pel carrer sense caminar, què pots utilitzar?", correct: "🚲", opts: ["🛏️", "🍞", "🧼", "🐱", "🎨"] },
    { q: "Vols escriure una carta, què necessites?", correct: "✏️", opts: ["🚗", "🍉", "🧸", "🐶", "🍕"] },
    { q: "Vols veure-hi millor a les fosques, què agafes?", correct: "🔦", opts: ["🍎", "📚", "🚲", "🐱", "🎨"] },
    { q: "Has de tallar una cartolina, què utilitzes?", correct: "✂️", opts: ["🍌", "🚗", "🧸", "📖", "🐟"] },
    { q: "Vols escoltar música, què pots fer servir?", correct: "🎧", opts: ["🔨", "🍎", "🐱", "🚲", "📚"] },
    { q: "Vols fer una fotografia d'un amic, què utilitzes?", correct: "📷", opts: ["🍕", "🛏️", "🎨", "🐶", "🚂"] },
    { q: "Necessites saber quina hora és, què mires?", correct: "⌚", opts: ["🍎", "📚", "🐱", "🚲", "🎈"] },
    { q: "Vols menjar una fruita groga, què tries?", correct: "🍌", opts: ["🚗", "🔨", "📖", "🧸", "🐟"] },
    { q: "Vols menjar una pizza per sopar, què esculls?", correct: "🍕", opts: ["📚", "🚲", "🎨", "🐱", "🔑"] },
    { q: "Vols encendre una espelma, què necessites?", correct: "🔥", opts: ["🍎", "🚗", "🧸", "📷", "🐶"] },
    { q: "Tens fred a l'hivern, què et poses?", correct: "🧥", opts: ["🍌", "🚲", "🎨", "📚", "🐱"] },
    { q: "Vols felicitar algú pel seu aniversari, què li portes?", correct: "🎁", opts: ["🚂", "🔨", "🧼", "🐟", "🍞"] },
    { q: "Vols bufar les espelmes d'aniversari, què hi ha davant teu?", correct: "🎂", opts: ["📚", "🚗", "🐶", "🎨", "🍉"] },
    { q: "Vols jugar a futbol, què necessites?", correct: "⚽", opts: ["📷", "🍌", "🔑", "🧸", "🐱"] },
    { q: "Vols jugar a bàsquet, què utilitzes?", correct: "🏀", opts: ["🚂", "📖", "🎨", "🐶", "🍎"] },
    { q: "Vols nedar a la piscina, què necessites?", correct: "🏊", opts: ["🛏️", "🚗", "📚", "🐱", "🍕"] },
    { q: "Vols viatjar molt ràpid entre ciutats, què agafes?", correct: "✈️", opts: ["🧸", "🍌", "📖", "🐟", "🎨"] },
    { q: "Vols navegar pel mar, què utilitzes?", correct: "⛵", opts: ["🚗", "🍞", "🔨", "📷", "🐱"] },
    { q: "Vols plantar una flor al jardí, què necessites?", correct: "🌱", opts: ["🚲", "🧸", "🍉", "📚", "🐶"] },
    { q: "Veus una carta a la bústia, què és?", correct: "✉️", opts: ["🍎", "🚗", "🎨", "🐟", "🔨"] },
    { q: "Vols enviar un missatge electrònic, què fas servir?", correct: "💻", opts: ["🍕", "🐱", "🚂", "📖", "🧼"] },
    { q: "Vols parlar amb algú que és lluny, què utilitzes?", correct: "📱", opts: ["🍌", "🎈", "🚲", "🐟", "📚"] },
    { q: "Vols menjar un entrepà, què agafes?", correct: "🥪", opts: ["🚗", "🔑", "🐶", "📷", "🎨"] },
    { q: "Vols beure llet a l'esmorzar, què necessites?", correct: "🥛", opts: ["📚", "🍕", "🚂", "🐱", "🔨"] },
    { q: "Vols cuinar una sopa, què utilitzes?", correct: "🍲", opts: ["🚲", "🧸", "📖", "🐟", "🎈"] },
    { q: "Vols tocar música amb un instrument de corda, què tries?", correct: "🎸", opts: ["🍎", "🚗", "🧼", "📚", "🐱"] },
    { q: "Vols tocar una melodia amb tecles, què utilitzes?", correct: "🎹", opts: ["🍌", "🚂", "📷", "🐟", "🔑"] },
    { q: "Vols cantar davant del públic, què necessites?", correct: "🎤", opts: ["🍕", "🚲", "🐶", "📖", "🧸"] },
    { q: "Vols observar les estrelles de prop, què utilitzes?", correct: "🔭", opts: ["🍎", "🚗", "🎨", "🐱", "📚"] },
    { q: "Vols veure coses molt petites, què utilitzes?", correct: "🔬", opts: ["🚂", "🍌", "📷", "🐟", "🧼"] },
    { q: "Vols portar la compra a casa, què agafes?", correct: "🛒", opts: ["📖", "🎈", "🚲", "🐶", "🍎"] },
    { q: "Vols seure per descansar, què utilitzes?", correct: "🪑", opts: ["🚗", "🔨", "📚", "🐱", "🎨"] },
    { q: "Vols guardar la roba, què utilitzes?", correct: "🧳", opts: ["🍌", "📷", "🐟", "🚂", "🧸"] },
    { q: "Vols decorar una festa, què penges?", correct: "🎈", opts: ["🍎", "🚲", "🔑", "📚", "🐶"] },
    { q: "Vols fer una videotrucada, què necessites?", correct: "📱", opts: ["🍕", "🚂", "🧼", "🐱", "🎨"] },
    { q: "Vols mirar una pel·lícula a casa, què encens?", correct: "📺", opts: ["🚗", "🍌", "📖", "🐟", "🔨"] },
    { q: "Vols escoltar la ràdio, què utilitzes?", correct: "📻", opts: ["📚", "🧸", "🚲", "🍎", "🐶"] },
    { q: "Vols fer un trencaclosques, què necessites?", correct: "🧩", opts: ["🚂", "🎨", "🐱", "🍕", "📷"] },
    { q: "Vols fer una festa amb música, què poses?", correct: "🎵", opts: ["🚗", "📚", "🐟", "🔨", "🍌"] },
    { q: "Vols anar de càmping i dormir fora, què muntes?", correct: "⛺", opts: ["📖", "🚲", "🧸", "🐶", "🍎"] },
    { q: "Vols refrescar-te a l'estiu, què menges?", correct: "🍦", opts: ["🚂", "🔑", "📚", "🐱", "🎨"] },
    { q: "Vols menjar una síndria fresca, què tries?", correct: "🍉", opts: ["🚗", "🧼", "📷", "🐟", "🍞"] },
    { q: "Vols menjar una maduixa, què agafes?", correct: "🍓", opts: ["📚", "🚲", "🐶", "🎈", "🔨"] },
    { q: "Vols menjar una taronja, què tries?", correct: "🍊", opts: ["🍕", "🐱", "📖", "🚂", "🧸"] },
    { q: "Vols menjar raïm, què agafes?", correct: "🍇", opts: ["🚗", "📚", "🎨", "🐟", "🔑"] },
    { q: "Vols menjar una pastanaga, què tries?", correct: "🥕", opts: ["🚲", "🍞", "📷", "🐶", "🧼"] },
    { q: "Vols esmorzar cereals, què necessites?", correct: "🥣", opts: ["🚂", "🎈", "📚", "🐱", "🔨"] },
    { q: "Vols beure un cafè calent, què agafes?", correct: "☕", opts: ["🚗", "🍌", "📖", "🐟", "🧸"] },
    { q: "Vols fer esport corrent, què et poses als peus?", correct: "👟", opts: ["📚", "🚲", "🐶", "🎨", "🍎"] },
    { q: "Vols protegir-te del sol a la platja, què et poses?", correct: "🧢", opts: ["🚂", "🔑", "📷", "🐱", "🍕"] },
    { q: "Vols veure el temps que farà, què consultes?", correct: "🌤️", opts: ["📚", "🚗", "🧸", "🐟", "🎈"] },
    { q: "Vols enviar un paquet, on el portes?", correct: "📮", opts: ["🍎", "🚲", "🔨", "🐶", "📖"] },
    { q: "Vols comptar números, què utilitzes?", correct: "🧮", opts: ["🚂", "🍌", "📷", "🐱", "🎨"] },
    { q: "Vols apuntar una cita important, què utilitzes?", correct: "📅", opts: ["🚗", "📚", "🐟", "🔑", "🍕"] },
    { q: "Vols saber on ets en un mapa, què mires?", correct: "🗺️", opts: ["🚲", "🎈", "🐶", "📖", "🧸"] },
    { q: "Vols cuinar unes torrades, què necessites?", correct: "🍞", opts: ["🚂", "📷", "🐱", "🎨", "🔨"] },
    { q: "Vols decorar un arbre de Nadal, què hi poses?", correct: "⭐", opts: ["🚗", "🍌", "📚", "🐟", "🧼"] },
    { q: "Vols fer un regal amb un llaç, què prepares?", correct: "🎁", opts: ["🚲", "📖", "🐶", "🎈", "🍎"] },
    { q: "Vols escriure a l'ordinador, què utilitzes?", correct: "⌨️", opts: ["🚂", "🔑", "📷", "🐱", "🍕"] },
    { q: "Vols imprimir un document, què necessites?", correct: "🖨️", opts: ["🚗", "📚", "🐟", "🎨", "🧸"] },
    { q: "Vols guardar informació digital, què utilitzes?", correct: "💾", opts: ["🚲", "🍌", "📖", "🐶", "🔨"] },
    { q: "Vols veure una hora concreta en un edifici, què mires?", correct: "🕒", opts: ["🚂", "📷", "🐱", "🍎", "🎈"] },
    { q: "Vols escoltar el so d'una campana, què sona?", correct: "🔔", opts: ["🚗", "📚", "🐟", "🎨", "🧸"] },
    { q: "Vols fer una celebració amb focs artificials, què veus?", correct: "🎆", opts: ["🚲", "📖", "🐶", "🍕", "🔑"] },
    { q: "Vols felicitar algú amb amor, què envies?", correct: "❤️", opts: ["🚂", "🍌", "📷", "🐱", "🎈"] },
    { q: "Vols mostrar que tens fred, quina cara fas?", correct: "🥶", opts: ["🚗", "📚", "🐟", "🎨", "🧸"] },
    { q: "Vols mostrar que tens molta gana, què penses?", correct: "🍔", opts: ["🚲", "📖", "🐶", "🔑", "🍎"] },
    { q: "Vols anar al metge perquè et trobes malament, on vas?", correct: "🏥", opts: ["🚂", "📷", "🐱", "🎨", "🧸"] },
    { q: "Vols aprendre coses noves, on vas?", correct: "🏫", opts: ["🚗", "📚", "🐟", "🍕", "🎈"] },
    { q: "Vols comprar aliments, on vas?", correct: "🏪", opts: ["🚲", "📖", "🐶", "🔨", "🍎"] },
    { q: "Vols veure animals exòtics, on vas?", correct: "🦁", opts: ["🚂", "📷", "🐱", "🎨", "🧸"] },
    { q: "Vols jugar amb una mascota molt comuna, quin animal tries?", correct: "🐶", opts: ["🚗", "📚", "🐟", "🍕", "🎈"] },
    { q: "Vols sentir el miol d'un animal domèstic, quin és?", correct: "🐱", opts: ["🚲", "📖", "🍎", "🔨", "🧸"] },
    { q: "Vols veure un animal que vola pel cel, quin és?", correct: "🐦", opts: ["🚂", "📷", "🐱", "🎨", "🍕"] },
    { q: "Vols veure un animal que viu a l'aigua, quin és?", correct: "🐟", opts: ["🚗", "📚", "🐶", "🎈", "🔑"] },
    { q: "Vols veure un animal molt gran amb trompa, quin és?", correct: "🐘", opts: ["🚲", "📖", "🍎", "🔨", "🧸"] },
    { q: "Vols veure un animal amb coll molt llarg, quin és?", correct: "🦒", opts: ["🚂", "📷", "🐱", "🎨", "🍕"] },
    { q: "Vols veure un animal que fa mel, quin és?", correct: "🐝", opts: ["🚗", "📚", "🐟", "🎈", "🔑"] },
    { q: "Vols veure un animal que salta i porta una bossa, quin és?", correct: "🦘", opts: ["🚲", "📖", "🍎", "🔨", "🧸"] },
    { q: "Vols veure un animal que viu al gel, quin és?", correct: "🐧", opts: ["🚂", "📷", "🐱", "🎨", "🍕"] },
    { q: "Vols veure un animal que camina molt lentament, quin és?", correct: "🐢", opts: ["🚗", "📚", "🐶", "🎈", "🔑"] }
];